// The app's icon set, mapped to Font Awesome 7 glyphs in two weights: `light`
// (the default everywhere) and `solid` (used to mark a selected/active state).
// Each app key (search, chevDown, …) keeps its name so every `<Icon name="…">`
// call site is unaffected; only the underlying glyph changes. Icons are imported
// one by one so the bundler tree-shakes everything else away. This name→glyph
// mapping is the source for scripts/gen-icons-page.mjs.

import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
    faMagnifyingGlass as lMagnifyingGlass,
    faCodeBranch as lCodeBranch,
    faChevronDown as lChevronDown,
    faChevronRight as lChevronRight,
    faLock as lLock,
    faRectangleTerminal as lRectangleTerminal,
    faLaptop as lLaptop,
    faFolder as lFolder,
    faUser as lUser,
    faEye as lEye,
    faCheck as lCheck,
    faTriangleExclamation as lTriangleExclamation,
    faCircleXmark as lCircleXmark,
    faCircle as lCircle,
    faLayerGroup as lLayerGroup,
    faSliders as lSliders,
    faCode as lCode,
    faDatabase as lDatabase,
    faFile as lFile,
    faPuzzlePiece as lPuzzlePiece,
    faGrid2 as lGrid2,
    faCircleInfo as lCircleInfo,
    faGripVertical as lGripVertical,
    faMoon as lMoon,
    faSun as lSun,
    faSidebarFlip as lSidebarFlip,
    faArrowRight as lArrowRight,
    faPlus as lPlus,
    faTrash as lTrash,
    faCodeCompare as lCodeCompare,
    faEyeSlash as lEyeSlash,
    faPlay as lPlay,
    faCodeMerge as lCodeMerge,
    faGear as lGear,
    faUpDownLeftRight as lUpDownLeftRight,
    faServer as lServer,
} from '@fortawesome/pro-light-svg-icons';
import {
    faMagnifyingGlass as sMagnifyingGlass,
    faCodeBranch as sCodeBranch,
    faChevronDown as sChevronDown,
    faChevronRight as sChevronRight,
    faLock as sLock,
    faRectangleTerminal as sRectangleTerminal,
    faLaptop as sLaptop,
    faFolder as sFolder,
    faUser as sUser,
    faEye as sEye,
    faCheck as sCheck,
    faTriangleExclamation as sTriangleExclamation,
    faCircleXmark as sCircleXmark,
    faCircle as sCircle,
    faLayerGroup as sLayerGroup,
    faSliders as sSliders,
    faCode as sCode,
    faDatabase as sDatabase,
    faFile as sFile,
    faPuzzlePiece as sPuzzlePiece,
    faGrid2 as sGrid2,
    faCircleInfo as sCircleInfo,
    faGripVertical as sGripVertical,
    faMoon as sMoon,
    faSun as sSun,
    faSidebarFlip as sSidebarFlip,
    faArrowRight as sArrowRight,
    faPlus as sPlus,
    faTrash as sTrash,
    faCodeCompare as sCodeCompare,
    faEyeSlash as sEyeSlash,
    faPlay as sPlay,
    faCodeMerge as sCodeMerge,
    faGear as sGear,
    faUpDownLeftRight as sUpDownLeftRight,
    faServer as sServer,
} from '@fortawesome/pro-solid-svg-icons';

export type IconVariant = 'light' | 'solid';

export const ICONS = {
    search: lMagnifyingGlass,
    repo: lCodeBranch,
    chevDown: lChevronDown,
    chevRight: lChevronRight,
    lock: lLock,
    terminal: lRectangleTerminal,
    laptop: lLaptop,
    folder: lFolder,
    user: lUser,
    eye: lEye,
    check: lCheck,
    alert: lTriangleExclamation,
    xcircle: lCircleXmark,
    circle: lCircle,
    layers: lLayerGroup,
    sliders: lSliders,
    code: lCode,
    db: lDatabase,
    file: lFile,
    puzzle: lPuzzlePiece,
    grid: lGrid2,
    info: lCircleInfo,
    grip: lGripVertical,
    moon: lMoon,
    sun: lSun,
    panel: lSidebarFlip,
    arrow: lArrowRight,
    plus: lPlus,
    trash: lTrash,
    compare: lCodeCompare,
    eyeoff: lEyeSlash,
    play: lPlay,
    diff: lCodeMerge,
    settings: lGear,
    move: lUpDownLeftRight,
    server: lServer,
} satisfies Record<string, IconDefinition>;

export type IconName = keyof typeof ICONS;

export const ICONS_SOLID = {
    search: sMagnifyingGlass,
    repo: sCodeBranch,
    chevDown: sChevronDown,
    chevRight: sChevronRight,
    lock: sLock,
    terminal: sRectangleTerminal,
    laptop: sLaptop,
    folder: sFolder,
    user: sUser,
    eye: sEye,
    check: sCheck,
    alert: sTriangleExclamation,
    xcircle: sCircleXmark,
    circle: sCircle,
    layers: sLayerGroup,
    sliders: sSliders,
    code: sCode,
    db: sDatabase,
    file: sFile,
    puzzle: sPuzzlePiece,
    grid: sGrid2,
    info: sCircleInfo,
    grip: sGripVertical,
    moon: sMoon,
    sun: sSun,
    panel: sSidebarFlip,
    arrow: sArrowRight,
    plus: sPlus,
    trash: sTrash,
    compare: sCodeCompare,
    eyeoff: sEyeSlash,
    play: sPlay,
    diff: sCodeMerge,
    settings: sGear,
    move: sUpDownLeftRight,
    server: sServer,
} satisfies Record<IconName, IconDefinition>;

/** Resolve an icon name to its glyph in the requested weight (light by default). */
export function resolveIcon(name: string, variant: IconVariant = 'light'): IconDefinition | undefined {
    const set = variant === 'solid' ? ICONS_SOLID : ICONS;
    return set[name as IconName];
}
